# Solving Linear Function using MLP(Multi-Layer Processing)

In [5]:
import tensorflow as tf
import numpy as np

from utils.support_tf import LogLevelManager as llm

In [7]:
llm.set(2)

In [8]:
train_x = np.array([[5], [-10], [9], [0], [4], [2]])
train_y = np.array([17, -28, 29, 2, 14, 8])   # train_y = train_x * 3 + 2
train_x.shape, train_x, train_y, train_y.shape

((6, 1),
 array([[  5],
        [-10],
        [  9],
        [  0],
        [  4],
        [  2]]),
 array([ 17, -28,  29,   2,  14,   8]),
 (6,))

## Training MLP Algorithm

In [12]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=(1,))
])
model.compile(optimizer="sgd", loss="mse", metrics=["mae"])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(train_x, train_y, epochs=4)

Epoch 1/4
1/1 [==============================] - 0s 7ms/step - loss: 0.0019 - mae: 0.0420
Epoch 2/4
1/1 [==============================] - 0s 5ms/step - loss: 0.0018 - mae: 0.0412
Epoch 3/4
1/1 [==============================] - 0s 5ms/step - loss: 0.0018 - mae: 0.0405
Epoch 4/4
1/1 [==============================] - 0s 5ms/step - loss: 0.0017 - mae: 0.0397


In [16]:
pred_mlp = model.predict(np.array([[1], [3]]))
pred_mlp

array([[ 4.959745],
       [10.963571]], dtype=float32)