In [1]:
import tensorflow as tf
import numpy as np

In [3]:
from utils.support_tf import LogLevelManager as llm
llm.set(2)

# tensor 생성

## tf.constant

In [12]:
# 리스트를 이용해 상수형 텐서를 생성함

t1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], dtype=tf.float64)
t1

<tf.Tensor: shape=(12,), dtype=float64, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])>

In [13]:
t1.numpy()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [14]:
for t in t1:
    print(t)

tf.Tensor(1.0, shape=(), dtype=float64)
tf.Tensor(2.0, shape=(), dtype=float64)
tf.Tensor(3.0, shape=(), dtype=float64)
tf.Tensor(4.0, shape=(), dtype=float64)
tf.Tensor(5.0, shape=(), dtype=float64)
tf.Tensor(6.0, shape=(), dtype=float64)
tf.Tensor(7.0, shape=(), dtype=float64)
tf.Tensor(8.0, shape=(), dtype=float64)
tf.Tensor(9.0, shape=(), dtype=float64)
tf.Tensor(10.0, shape=(), dtype=float64)
tf.Tensor(11.0, shape=(), dtype=float64)
tf.Tensor(12.0, shape=(), dtype=float64)


In [16]:
t2 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], shape=(3,2,2), dtype=tf.float64)
for t in t2:
    print(t)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[ 9. 10.]
 [11. 12.]], shape=(2, 2), dtype=float64)


# tensor merge

## tf.concat

In [4]:
t1 = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
t2 = [[7, 8, 9], [10, 11, 12]]
type(t1), type(t2)

(tensorflow.python.framework.ops.EagerTensor, list)

In [5]:
t3 = tf.concat([t1, t2], axis=0)
t4 = tf.concat([t1, t2], axis=1)
t3, t4

(<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 6), dtype=float32, numpy=
 array([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]], dtype=float32)>)

## tf.stack

In [7]:
t5 = tf.stack(t1, axis=0, name="tensor5")
t6 = tf.stack(t1, axis=1)
t5, t6

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 4.],
        [2., 5.],
        [3., 6.]], dtype=float32)>)

In [8]:
t7 = tf.stack([t1, t2], axis=0)
t8 = tf.stack([t1, t2], axis=1)
t7, t8

(<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],
 
        [[ 7.,  8.,  9.],
         [10., 11., 12.]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[ 1.,  2.,  3.],
         [ 7.,  8.,  9.]],
 
        [[ 4.,  5.,  6.],
         [10., 11., 12.]]], dtype=float32)>)