# tf.keras.layers

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
from utils.support_tf import LogLevelManager as llm
llm.set(2)

## Embedding

In [3]:
temp_input = np.array([[1.5, 2., 0], [8, 2., 6.]])  # (2,3)
temp_output = tf.keras.layers.Embedding(
    # 입력값중 가장 큰 수+1,
    # 임베딩이 주로 단어처리 시 사용하기 때문에 사전의 크기와 추가된 특수문자(PAD,UNK 등))가
    # 모두 일련번호로 되어 있어 대부분 설명이 단어집합의 크기라고 하지만,
    # (다시 말하면 0부터 시작하는 일련번호이기 때문에 가장 큰 수가 단어집합의 크기)
    # 정확하게는 입력값중 가장 큰 수가 맞을 듯
    # 아래와 같이 7을 입력하면, 위에 있는 8은 임베딩되지 않음.
    input_dim=7, 
    # 각 숫자를 몇 차원으로 의미있게 만들지 정함
    output_dim=4, 
    # 각 입력 데이터의 길이(지정하지 않아도 됨)
    input_length=len(temp_input[0]),
    # 기본값은 'False'이며, 'True'로 처리하면,
    # <PAD>값(= 보통 0)을 임베딩은 하지만, 
    # 패딩 데이터라고 지정해 모델링에서 사용하지 않도록 지정함(아래 참조).
    mask_zero=True)(temp_input)

In [4]:
temp_output

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-0.023783  , -0.02757638,  0.03147807, -0.04107536],
        [-0.02517281,  0.04083048,  0.01646448, -0.01874264],
        [-0.0452969 ,  0.03383848,  0.03071577,  0.02956183]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [-0.02517281,  0.04083048,  0.01646448, -0.01874264],
        [ 0.04191061, -0.04902036,  0.04034099, -0.04398514]]],
      dtype=float32)>

In [6]:
temp_output._keras_mask

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True, False],
       [ True,  True,  True]])>