# tf.keras.layers

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
from utils.support_tf import LogLevelManager as llm
llm.set(2)

## Embedding

In [7]:
temp_input = np.array([[1.5, 2., 0], [8, 2., 6.]])  # (2,3)
temp_output = tf.keras.layers.Embedding(
    # 입력값중 가장 큰 수+1,
    # 임베딩이 주로 단어처리 시 사용하기 때문에 사전의 크기와 추가된 특수문자(PAD,UNK 등))가
    # 모두 일련번호로 되어 있어 대부분 설명이 단어집합의 크기라고 하지만,
    # (다시 말하면 0부터 시작하는 일련번호이기 때문에 가장 큰 수가 단어집합의 크기)
    # 정확하게는 입력값중 가장 큰 수가 맞을 듯
    # 아래와 같이 7을 입력하면, 위에 있는 8은 임베딩되지 않음.
    input_dim=7, 
    # 각 숫자를 몇 차원으로 의미있게 만들지 정함
    output_dim=4, 
    # 각 입력 데이터의 길이(지정하지 않아도 됨)
    input_length=len(temp_input[0]),
    # 기본값은 'False'이며, 'True'로 처리하면,
    # <PAD>값(= 보통 0)을 임베딩은 하지만, 
    # 패딩 데이터라고 지정해 모델링에서 사용하지 않도록 지정함(아래 참조).
    mask_zero=True)(temp_input)

: 

In [5]:
temp_output

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 0.03734512, -0.00339558,  0.02476282, -0.02638793],
        [-0.03018248, -0.04443945, -0.01219732,  0.04769332],
        [ 0.0235932 ,  0.02549801, -0.04232333,  0.03311655]],

       [[ 0.        ,  0.        ,  0.        ,  0.        ],
        [-0.03018248, -0.04443945, -0.01219732,  0.04769332],
        [-0.00739679, -0.04314042,  0.01438897, -0.04950527]]],
      dtype=float32)>

In [6]:
temp_output._keras_mask

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True, False],
       [ True,  True,  True]])>